RUNNING = main
ifeq ($(OS),Windows_NT)
    OS_TYPE := windows
    CXX := g++
    RM_FILE := del /Q /F
    RM_DIR  := rd /S /Q
    EXE_SUFFIX := .exe
else
    OS_TYPE := linux
    CXX := g++
    RM_FILE := rm -f
    RM_DIR  := rm -rf
    EXE_SUFFIX :=
endif
CXXFLAGS := -Wall -Wextra -std=c++17
DEBUG_CXXFLAGS := -g -O0
RELEASE_CXXFLAGS := -O2 -DNDEBUG
SRC_DIR := src
OBJ_DIR := obj
BIN_DIR := bin


INCLUDE_DIRS := -I$(SRC_DIR)/include

LIB_DIRS := -L$(SRC_DIR)/lib


LIBS := -lm

SRCS := $(wildcard $(SRC_DIR)/*.cpp)
OBJS := $(patsubst $(SRC_DIR)/%.cpp,$(OBJ_DIR)/%.o,$(SRCS))
TARGET := $(BIN_DIR)/$(RUNNING)$(EXE_SUFFIX)